version: 1.0.{build}
image: Visual Studio 2017
environment:
  major: 1
  minor: 0
  patch: 1
configuration: Release
init:
  - git config --global core.autocrlf true
  - ps: |
      $isCI = $Env:APPVEYOR_REPO_TAG -eq $false
      $isBranch = $isCI -and ($Env:APPVEYOR_REPO_BRANCH -ne 'master')
      $branchSuffix = "$(if ($isBranch) { '-' + $Env:APPVEYOR_REPO_BRANCH } else { $null })"
      $Env:VersionPrefix = "$($Env:major).$($Env:minor).$($Env:patch)"
      $Env:VersionSuffix = "$(if ($isCI) { $Env:APPVEYOR_BUILD_NUMBER + $branchSuffix } else { $null })"
      appveyor UpdateBuild -Version "$($Env:VersionPrefix)$(if ($isCI) { '-' } else { $null })$($Env:VersionSuffix)"
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(VersionPrefix).0
  assembly_file_version: $(VersionPrefix).$(APPVEYOR_BUILD_NUMBER)
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
before_build:
  - dotnet restore src
build:
  project: src/ClaymoreMiner.RemoteManagement.sln
  verbosity: minimal  
artifacts:
  - path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: KYazkCEi9oMn1AALPvX9WRLKoBfGmk7WNsAxs+sfmOov/pSQcS/48m0Dl8aV3hX8
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true
