image: Visual Studio 2017
environment:
  major: 1
  minor: 0
  patch: 2
configuration: Release
init:
- ps: |
    $isCI = $Env:APPVEYOR_REPO_TAG -eq $false
    $isBranch = $isCI -and ($Env:APPVEYOR_REPO_BRANCH -ne 'master')
    $branchSuffix = "$(if ($isBranch) { '-' + $Env:APPVEYOR_REPO_BRANCH } else { $null })"
    $buildPlanVersion = "$($Env:major).$($Env:minor).$($Env:patch)"
    $Env:VersionPrefix = "$(if ($isCI) { $buildPlanVersion } else { $Env:APPVEYOR_REPO_TAG_NAME })"
    $Env:VersionSuffix = "$(if ($isCI) { $branchSuffix + $Env:APPVEYOR_BUILD_NUMBER } else { $null })"
    appveyor UpdateBuild -Version "$($Env:VersionPrefix)$(if ($isCI) { '-' } else { $null })$($Env:VersionSuffix)"
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(VersionPrefix).0
  assembly_file_version: $(VersionPrefix).$(APPVEYOR_BUILD_NUMBER)
  assembly_informational_version: $(VersionPrefix)
nuget:
  project_feed: true
before_build:
- dotnet restore src
build:
  project: src/ClaymoreMiner.RemoteManagement.sln
  verbosity: minimal
test_script:
- nunit3-console ./src/ClaymoreMiner.RemoteManagement.Tests/bin/Release/netcoreapp2.0/ClaymoreMiner.RemoteManagement.Tests.dll --result=myresults.xml;format=AppVeyor
artifacts:
  - path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: KYazkCEi9oMn1AALPvX9WRLKoBfGmk7WNsAxs+sfmOov/pSQcS/48m0Dl8aV3hX8
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true